### ISSUE TITLE
我并不知道怎么放入自己程序中使用，我拷贝了progress.dart文件放入自己项目中，调用的什么并没有什么用

### ISSUE THREAD

**Issue by tianyuming0329** [mjl0602/OVProgressHUD#8]

**Comment by mjl0602** [comment]
Add this to your package's pubspec.yaml file:
把如下字段加入你的`pubspec.yaml`文件：
```
dependencies:
  flutter:
    sdk: flutter
  // 添加下面这一行
  ovprogresshud: any
```
然后运行`flutter packages get`即可
